apply_time_parametrization_server:
  ros__parameters:
    action_name: apply_time_parametrization
    planning_service: /plan_kinematic_path
    planning_service_wait_sec: 2.0
    robot_description_param: robot_description
    group_configs_yaml: |
      - group_name: "ur_robot"
        resample_dt: 0.002
        path_tolerance: 0.001
        min_angle_change: 0.001